quarkus.datasource.db-kind=postgresql

#quarkus.datasource.jdbc.url=dev
#quarkus.datasource.username=dev
#quarkus.datasource.password=dev
quarkus.hibernate-orm.schema-management.strategy = update

quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.roles.admin=admin
quarkus.security.users.embedded.users.admin=password
quarkus.http.port=8081