quarkus.datasource.db-kind=postgresql

quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d99v5ibeo5us7396po30-a.frankfurt-postgres.render.com:5432/tembdb
quarkus.datasource.username=dev
quarkus.datasource.password=dev
dev-with-data.quarkus.hibernate-orm.schema-management.strategy = update
quarkus.http.port=8081